apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ciao-ingress
  namespace: ciao
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: k8s.ciao.ashkar.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend: 
          service: 
            name: apigw-service
            port: 
              number: 30001